import fs from 'node:fs';

console.log('fs', 'write' in fs);

export const robotList = [
  {
    id: 1,
    name: 'Fink',
    type: 'Lime Robot',
    price: '456',
    info: 'Fink may become your next best robot friend. It likes to listen to your surely very interesting thoughts and be your light at the end of the tunnel, when life is hard on you. Also it comes with a soft carpet for you two to relax on!',
  },
  {
    id: 2,
    name: 'Tivi',
    type: 'Red Lime Robot',
    price: '365',
    info: 'Tivi is our classic. First introduced as a portable TV, it can do so much more by now: it is a portable heater, it can peel oranges (no grapefruits!) and feed your bird.',
  },
  {
    id: 3,
    name: 'Licorice',
    type: 'Gummi Bear Robot',
    price: '710',
    info: 'Elit Cubilia Ultricies Duis Curabitur Elit Porta Vulputate Aenean Interdum Mauris Maecenas Bibendum Cras Mauris Venenatis Nam Conubia Posuere Himenaeos Placerat Dapibus Pretium Consectetur.',
  },
  {
    id: 4,
    name: 'Freaky',
    type: 'Dance Robot',
    price: '432',
    info: "I think u freaky and I like it a lot - that's Freakys motto. It will be happy to accompany you to all the raves you wish to go to. It comes with a practical built-in pill box and first aid kit.",
  },
  {
    id: 5,
    name: 'Jumpy',
    type: 'Productivity Lime Robot',
    price: '399',
    info: 'Elit Cubilia Ultricies Duis Curabitur Elit Porta Vulputate Aenean Interdum Mauris Maecenas Bibendum Cras Mauris Venenatis Nam Conubia Posuere Himenaeos Placerat Dapibus Pretium Consectetur.',
  },
  {
    id: 6,
    name: 'Helis',
    type: 'Productivity Productivity Robots',
    price: '1560',
    info: 'Sick of telling your child what to do? Parenting exhausts your beautiful mind and strong body? Then trust our Helis! They are more than happy to educate, wake up, console, feed, scold and love your sweethearts for you!',
  },
  {
    id: 7,
    name: 'Fesha',
    type: 'Beauty and Confidence Robot',
    price: '870',
    info: "Isn't it beautiful? Doesn't it look content? Well, that's because it is. If you suffer from a low self-esteem, Fesha can help in so may ways: correct your posture, remove body hair while you sleep, tell you to love yourself EVERY DAY or massage your wrinkles. Get your shit together - today!",
  },
  {
    id: 8,
    name: 'Marty',
    type: 'Pink-eyed Gummi Bear Robot',
    price: '870',
    info: "Isn't it beautiful? Doesn't it look content? Well, that's because it is. If you suffer from a low self-esteem, Fesha can help in so may ways: correct your posture, remove body hair while you sleep, tell you to love yourself EVERY DAY or massage your wrinkles. Get your shit together - today!",
  },
  {
    id: 9,
    name: 'Sam',
    type: 'Drag along Robot',
    price: '468',
    info: 'Elit Cubilia Ultricies Duis Curabitur Elit Porta Vulputate Aenean Interdum Mauris Maecenas Bibendum Cras Mauris Venenatis Nam Conubia Posuere Himenaeos Placerat Dapibus Pretium Consectetur.',
  },
  {
    id: 10,
    name: 'Ines',
    type: 'Modular Gummi Bear Robot',
    price: '846',
    info: 'Elit Cubilia Ultricies Duis Curabitur Elit Porta Vulputate Aenean Interdum Mauris Maecenas Bibendum Cras Mauris Venenatis Nam Conubia Posuere Himenaeos Placerat Dapibus Pretium Consectetur.',
  },
  {
    id: 11,
    name: 'Boulevard',
    type: 'Paris Robot',
    price: '777',
    info: 'Elit Cubilia Ultricies Duis Curabitur Elit Porta Vulputate Aenean Interdum Mauris Maecenas Bibendum Cras Mauris Venenatis Nam Conubia Posuere Himenaeos Placerat Dapibus Pretium Consectetur.',
  },
  {
    id: 12,
    name: 'Ninja',
    type: 'Green Point Robot',
    price: '866',
    info: 'Elit Cubilia Ultricies Duis Curabitur Elit Porta Vulputate Aenean Interdum Mauris Maecenas Bibendum Cras Mauris Venenatis Nam Conubia Posuere Himenaeos Placerat Dapibus Pretium Consectetur.',
  },
  {
    id: 13,
    name: 'Flyperson',
    type: 'Cupboard Robot',
    price: '589',
    info: 'Elit Cubilia Ultricies Duis Curabitur Elit Porta Vulputate Aenean Interdum Mauris Maecenas Bibendum Cras Mauris Venenatis Nam Conubia Posuere Himenaeos Placerat Dapibus Pretium Consectetur.',
  },
  {
    id: 14,
    name: 'Dorfer',
    type: 'Lost Robot',
    price: '347',
    info: 'Elit Cubilia Ultricies Duis Curabitur Elit Porta Vulputate Aenean Interdum Mauris Maecenas Bibendum Cras Mauris Venenatis Nam Conubia Posuere Himenaeos Placerat Dapibus Pretium Consectetur.',
  },
  {
    id: 15,
    name: 'Peel-o',
    type: 'Juice Robot',
    price: '943',
    info: 'Elit Cubilia Ultricies Duis Curabitur Elit Porta Vulputate Aenean Interdum Mauris Maecenas Bibendum Cras Mauris Venenatis Nam Conubia Posuere Himenaeos Placerat Dapibus Pretium Consectetur.',
  },
  {
    id: 16,
    name: 'Judith',
    type: 'Light Switch Robot',
    price: '943',
    info: 'Elit Cubilia Ultricies Duis Curabitur Elit Porta Vulputate Aenean Interdum Mauris Maecenas Bibendum Cras Mauris Venenatis Nam Conubia Posuere Himenaeos Placerat Dapibus Pretium Consectetur.',
  },
  {
    id: 17,
    name: 'Barrbara',
    type: 'Translation Robot',
    price: '1056',
    info: 'Elit Cubilia Ultricies Duis Curabitur Elit Porta Vulputate Aenean Interdum Mauris Maecenas Bibendum Cras Mauris Venenatis Nam Conubia Posuere Himenaeos Placerat Dapibus Pretium Consectetur.',
  },
  {
    id: 18,
    name: 'Lightning',
    type: 'Sporting Robot',
    price: '729',
    info: 'Elit Cubilia Ultricies Duis Curabitur Elit Porta Vulputate Aenean Interdum Mauris Maecenas Bibendum Cras Mauris Venenatis Nam Conubia Posuere Himenaeos Placerat Dapibus Pretium Consectetur.',
  },
  {
    id: 19,
    name: 'Antler',
    type: 'Deer Robot',
    price: '444',
    info: 'Elit Cubilia Ultricies Duis Curabitur Elit Porta Vulputate Aenean Interdum Mauris Maecenas Bibendum Cras Mauris Venenatis Nam Conubia Posuere Himenaeos Placerat Dapibus Pretium Consectetur.',
  },
  {
    id: 20,
    name: 'Funky',
    type: 'Wild Dance Robot',
    price: '729',
    info: 'Elit Cubilia Ultricies Duis Curabitur Elit Porta Vulputate Aenean Interdum Mauris Maecenas Bibendum Cras Mauris Venenatis Nam Conubia Posuere Himenaeos Placerat Dapibus Pretium Consectetur.',
  },
  {
    id: 21,
    name: 'Hundl',
    type: 'Doge Robot',
    price: '929',
    info: 'Elit Cubilia Ultricies Duis Curabitur Elit Porta Vulputate Aenean Interdum Mauris Maecenas Bibendum Cras Mauris Venenatis Nam Conubia Posuere Himenaeos Placerat Dapibus Pretium Consectetur.',
  },
  {
    id: 22,
    name: 'Rooibos',
    type: 'Praying Mantis Robot',
    price: '729',
    info: 'Elit Cubilia Ultricies Duis Curabitur Elit Porta Vulputate Aenean Interdum Mauris Maecenas Bibendum Cras Mauris Venenatis Nam Conubia Posuere Himenaeos Placerat Dapibus Pretium Consectetur.',
  },
];
